import type { Metadata } from "next";
import { Raleway, Bitcount_Prop_Single } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const bitcountPropSingle = Bitcount_Prop_Single({
  variable: "--font-bitcount-prop-single",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${bitcountPropSingle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
